### ISSUE TITLE
[Crash] After using Meru's D-attack

### ISSUE THREAD

**Issue by DrewUniverse** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#455] opened 2023-04-30 02:30 UTC
Was targeting a Dark Elf that I summoned to battle from the World Map (encounter 133). Crash during D-attack timer revolutions. 

```21:28:35.524 [Hardware legend.game.scripting.ScriptManager:91] INFO : Allocating script index 31 (AttackHitFlashEffect0c)
21:28:35.524 [Hardware legend.game.scripting.ScriptState:190] INFO : Loading script Do nothing into index 31 (entry point 0x0)
21:28:35.525 [Hardware legend.game.combat.Bttl_800e:1710] INFO : Allocating effect manager 31 for AttackHitFlashEffect0c (parent: 26) from legend.game.combat.Bttl_800e.allocateAttackHitFlashEffect(Bttl_800e.java:2088)
21:28:35.526 [Hardware legend.game.scripting.ScriptState:223] INFO : Deallocating script 21 children
21:28:35.526 [Hardware legend.game.scripting.ScriptState:205] INFO : Deallocating script state 21
21:28:35.526 [Hardware legend.game.combat.Bttl_800e:1629] INFO : Deallocating effect manager 21
21:28:35.575 [Hardware legend.game.scripting.ScriptManager:129] ERROR: Script 12 crashed!
21:28:35.575 [Hardware legend.game.scripting.ScriptManager:130] ERROR: File 4248/1[3009]
21:28:35.576 [Hardware legend.game.scripting.ScriptManager:131] ERROR: Parameters:
21:28:35.576 [Hardware legend.game.scripting.ScriptManager:132] ERROR:   Op param: 0xee
21:28:35.577 [Hardware legend.game.scripting.ScriptManager:134] ERROR:   1: script[0xbca] 0x1
21:28:35.577 [Hardware legend.game.scripting.ScriptManager:134] ERROR:   2: script[12].storage[30] 8
21:28:35.577 [Hardware legend.game.scripting.ScriptManager:134] ERROR:   3: script[12].storage[9] 251723565
21:28:35.577 [Hardware legend.game.scripting.ScriptManager:134] ERROR:   4: script[0xbcd] 0x0
21:28:35.577 [Hardware legend.game.scripting.ScriptManager:134] ERROR:   5: script[0xbce] 0x0
21:28:35.577 [Hardware legend.game.scripting.ScriptManager:134] ERROR:   6: script[0xbcf] 0x0
21:28:35.577 [Hardware legend.game.scripting.ScriptManager:134] ERROR:   7: script[0xbd0] 0x0
21:28:35.577 [Hardware legend.game.scripting.ScriptManager:137] ERROR: Storage:
21:28:35.577 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   1: 0xc
21:28:35.577 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   2: 0xffffffff
21:28:35.577 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   3: 0xffffffff
21:28:35.577 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   4: 0xffffffff
21:28:35.577 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   5: 0xffffffff
21:28:35.577 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   6: 0xffffffff
21:28:35.577 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   7: 0xffffffff
21:28:35.577 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   8: 0x90000
21:28:35.577 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   9: 0x6
21:28:35.578 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   10: 0xf00ff2d
21:28:35.578 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   11: 0x7e200
21:28:35.578 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   12: 0x0
21:28:35.578 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   13: 0x242200
21:28:35.578 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   14: 0xffffffff
21:28:35.578 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   15: 0xffffffff
21:28:35.578 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   16: 0xffffffff
21:28:35.578 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   17: 0xffffffff
21:28:35.578 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   18: 0xffffffff
21:28:35.578 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   19: 0x1a
21:28:35.578 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   20: 0xe
21:28:35.578 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   21: 0xf
21:28:35.578 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   22: 0x1600
21:28:35.578 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   23: 0xffffffff
21:28:35.578 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   24: 0x10
21:28:35.578 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   25: 0x64
21:28:35.578 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   26: 0xfffffce0
21:28:35.578 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   27: 0xffffffff
21:28:35.578 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   28: 0xffffffff
21:28:35.578 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   29: 0xb
21:28:35.578 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   30: 0xd
21:28:35.578 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   31: 0x8
21:28:35.578 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   32: 0xc
21:28:35.578 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   33: 0xffffffff
21:28:35.578 [Hardware legend.game.scripting.ScriptManager:142] ERROR: Call stack:
21:28:35.579 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   1: 2735
21:28:35.579 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   2: 0
21:28:35.579 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   3: 0
21:28:35.579 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   4: 0
21:28:35.579 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   5: 0
21:28:35.579 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   6: 0
21:28:35.579 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   7: 0
21:28:35.579 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   8: 0
21:28:35.579 [Hardware legend.core.gpu.Gpu:452] ERROR: Shutting down due to GPU exception:
java.lang.RuntimeException: An error occurred while ticking script 12
        at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:151)
        at legend.game.scripting.ScriptManager.tick(ScriptManager.java:23)
        at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:584)
        at legend.game.Scus94491BpeSegment.lambda$gameLoop$45(Scus94491BpeSegment.java:510)
        at legend.core.gpu.Gpu.lambda$setStandardRenderer$8(Gpu.java:502)
        at legend.core.gpu.Gpu.lambda$run$7(Gpu.java:437)
        at legend.core.opengl.Context.draw(Context.java:91)
        at legend.core.opengl.Window$Events.onDraw(Window.java:635)
        at legend.core.opengl.Window.run(Window.java:262)
        at legend.core.gpu.Gpu.run(Gpu.java:450)
        at legend.core.GameEngine.start(GameEngine.java:216)
        at legend.game.Main.main(Main.java:23)
        at legend.game.MainWindows.main(MainWindows.java:33)
Caused by: legend.core.memory.IllegalAddressException: There is no memory segment at 1e91a1c6 (address: 9e91a1c6)
        at legend.core.memory.Memory.getSegment(Memory.java:118)
        at legend.core.memory.Memory$MemoryValue.getSegment(Memory.java:362)
        at legend.core.memory.Memory$MemoryValue.get(Memory.java:419)
        at legend.game.Scus94491BpeSegment.playSound(Scus94491BpeSegment.java:2813)
        at legend.game.Scus94491BpeSegment.playBobjSound(Scus94491BpeSegment.java:2629)
        at legend.game.Scus94491BpeSegment.scriptPlayBobjSound(Scus94491BpeSegment.java:2886)
        at legend.game.scripting.ScriptState.scriptExecuteSubFunc(ScriptState.java:894)
        at legend.game.scripting.ScriptState.runOp(ScriptState.java:530)
        at legend.game.scripting.ScriptState.executeFrame(ScriptState.java:458)
        at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:125)
        ... 12 more
21:28:35.580 [Hardware legend.core.opengl.Window:92] INFO : Shutting down...

**Comment by DrewUniverse** [comment] 2023-04-30 14:43
tfz  brought up a good question about whether I had automatic Dragoon additions enabled - the answer was yes. I forgot to turn off that setting before doing the revolutions manually.

**Comment by theflyingzamboni** [comment] 2023-05-01 15:46
Duplicate of #431

**Closed by theflyingzamboni** 2023-05-01 15:46 UTC
