### ISSUE TITLE
Crash when leaving Menu

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#304] opened 2023-03-03 08:49 UTC
when i was leaving Menu using ESC key... i pressed too fast or too much (i think, idk exactly) and the game crashed...
i believe to be that because it was fast or much... maybe i'm wrong...
[Crash_Menu_Fast.txt](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/files/10880182/Crash_Menu_Fast.txt)

**Comment by dragoonsouls** [comment] 2023-03-03 08:49
as an adding i travelled from Undersea Cavern (Regole Lair) to Home of Gigantos to farm some sachets... this happened in Home of Gigantos

**Comment by dragoonsouls** [comment] 2023-03-03 08:50
during that i been playing around 2 hours

**Comment by Ink230** [comment] 2023-03-03 12:16
If the issue is the missing OOB check in handleEncounter, note it exists in both SMap and WMap

So an invalid index was given by either:
• Coming out of the menu too slowly
• Being in battle before menu or battle starting instantly on menu close
• Invalid submap slice on the map (Doom must have moved slightly after ESC)
 • Standing past an entrance / out of bounds ?

If it should never be -1 (can't see it set to this in the src), then that is interesting. 

We can force a similar crash by using the Debugger and going out of bounds.

**Comment by Ink230** [comment] 2023-03-05 10:01
Spyrokid on Discord reported the same issue.

## Details at the time
• Seems to occur >2 hours of play time
• Occurred on Giganto map and Fort Magrad

## Investigation
Left my game running for 4 hours. Spammed the menu and closing it long enough to get into battle, did battle, ended battle and spammed again. Upon viewing the log:

![image](https://user-images.githubusercontent.com/29797557/222952417-8d976698-3d63-447b-ac99-b7f99a00adc8.png)

• -1 index was observed **ONCE**
• I'm not sure when it occurred 
• Game did not crash, game corrected its index to match the submap as normal and proceeded as normal

In the same instance of the game, I got it again.

![image](https://user-images.githubusercontent.com/29797557/222952962-b3ee77fa-5358-45ed-9a5d-e097e7f160d9.png)

• Occurred 5 menu closings after battle ended whilst spamming

Obviously a good deduction is that it occurs from opening and closing the menu quickly. To test,

• Spammed menu on a fresh instance with no battles
• Spammed menu on a fresh instance after a battle
• Spam both on a fresh instance

• Could not generate a -1 index on a fresh instance pre-battle
• Could infrequently generate the -1 index if I spammed menu openings post-battle

Note the -1 index takes awhile to show up (I guess waiting for the menu logic to stop and the submap logic to begin) after having closed the menu and not continuing the spam.

## Code for testing

```
    if(index_80052c38.get() <0)
      System.out.println("index: " + index_80052c38.get());

    if((index_80052c38.get() < 0x40L && index_80052c38.get() >= 0) && arr_800cb460.get(index_80052c38.get()).get() != 0) {
      return 0;
    }
```
*SMap.java, handleEncounters()*

The second if statement is a fix for the missing OOB check. Again, if the index should never be -1 then this is not a solution. However, its unclear if the game decides to use -1 as a normal check that we are not accounting for.

I also call index_800xxx.get() from inside the main menu to log the index in there. The index in the menu is always correct to the submap as before the menu was opened.


## Forcing -1

• We can force index -1 by going out of bounds via the debugger
• This causes a script crash immediately after if the above solution is in use
• Thus the bug is most likely not related to scripting or out of bounds / collision issues 

## Take away

• Can occur at any lifetime of the instance
• Can occur on any map
• Can be reproduced by opening and closing the menu *fast* (easier/only possible after a battle)
• Does not result in a script crash and self-corrects itself
• Index while in menu is always the correct submap, the index change seems to occur on submap load

• Thus, whatever is occurring from the menu being closed and the submap logic loading/starting to re-render / start checks again is most likely setting the index to -1 somehow
• If the character's position is ever reset in this time, there could be a slice in time that handleEncounter runs too early and gets a -1

**Comment by Ink230** [comment] 2023-03-05 10:08
![image](https://user-images.githubusercontent.com/29797557/222953999-0fea3347-094c-4cb6-87e6-a2653913c3e5.png)

Confirmation it appears to only occur on one single frame.

Note after battle, if you spam menu openings and closings, you can delay the submap handleEncounter from loading. Before battle, you will always get at least 2 frames of output of the index. After battle ends, you can delay the output of the index indefinitely while spamming the menu, despite the submap having been loaded. 

The issue is probably located within this submap encounterHandle delay you can do after battle by spamming the menu. As, this explains the prior behaviour to reproduce it.

**Comment by Ink230** [comment] 2023-03-05 16:04
Probable cause at the bottom w/ no straight-forward solution.

Through the process of elimination when index -1 occurs, narrowed it down to this:

FUN_800ea84c =>
sobjs_800c6880[0].innerStruct_00.ui_16c

Which can be set to < 0 by a callback that is attached to
_800d1a90 in the function
FUN_800ea974

Which is called by
executeSmapLoadingStage_2
by inside of a switch case 
_800cab24.set(FUN_800ea974(_800caaf4.get()));

_800caaf4 is only set to the value of
submapCut_80052c30.get()

Which is only set by either:
• gameState_800babc8.submapCut_a8.get()
• script.params_20[2].get() => FUN_800e6ce0
• _800c6860
• script engine

A rough flow line by line is (lines approx)
4255 first one hit in smap post battle
4243
4385
6393
4404 (last one before menu opens)
4464 (after opening menu after battle)

W/ 6338 being called *immediately*.

However, all of that stuff is one giant circle of assignment for post-battle behaviour. So none of that seems to be the issue.


So
sobjs_800c6880 looks to be the culprit.

The easiest find is:
GameVarArrayParam.ava
```
case 64 -> SMap.sobjs_800c6880[this.arrIndex] != null ? SMap.sobjs_800c6880[this.arrIndex].index : -1;
```
Which pairs with:

SMap.java
```
unloadSmap()
submapControllerState_800c6740.deallocateWithChildren();
...
sobjs_800c6880[i].deallocateWithChildren();
```

So TLDR

Post-battle destructuring => SMap Loads stuff (like line 6338 in SMap which we can see being called in console) => sobjs_800c6880 is null and doesn't get set yet => Open Menu, close menu => SMap detects handleEncounter needs to run but index is -1 from sobjs being null => SMap Loads again partially => sobjs still null, -1 => Stop spamming menu, SMap can fully load itself and assign value to sobjs.

The menu opens too fast for the SMap loader to complete. 
Alternatively, the SMap loads fast enough and the Menu loads fast enough but the script engine is too slow.

Game logic takes too many frames, input frames get queued ahead of game logic => index -1.

The only hangup is that when changing case 64 to return as -2, -1 still appears. I'm not sure if the script engine is handling that, or if sobjs is being defaulted to -1 down the call tree in java.

**Closed** 2023-03-09 20:31 UTC
