### ISSUE TITLE
Divine Dragon cutscene crash

### ISSUE THREAD

**Issue by Zychronix** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#276] opened 2023-02-26 00:18 UTC
on branch main.tmd
java.lang.ArrayIndexOutOfBoundsException: Index 20 out of bounds for length 20
	at legend.game.Scus94491BpeSegment_8002.applyModelPartTransforms(Scus94491BpeSegment_8002.java:672)
	at legend.game.Scus94491BpeSegment_8002.loadModelStandardAnimation(Scus94491BpeSegment_8002.java:730)
	at legend.game.Scus94491BpeSegment_8002.FUN_80020718(Scus94491BpeSegment_8002.java:395)
	at legend.game.Scus94491BpeSegment_8002.initModel(Scus94491BpeSegment_8002.java:421)
	at legend.game.combat.Bttl_800c.FUN_800c952c(Bttl_800c.java:1750)
	at legend.game.combat.Bttl_800c.bobjTicker(Bttl_800c.java:2409)
	at legend.game.scripting.ScriptState.tick(ScriptState.java:170)
	at legend.game.scripting.ScriptManager.executeScriptTickers(ScriptManager.java:171)
	at legend.game.scripting.ScriptManager.tick(ScriptManager.java:24)
	at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:796)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:722)
	at legend.core.gpu.Gpu.lambda$setStandardRenderer$8(Gpu.java:508)
	at legend.core.gpu.Gpu.lambda$run$7(Gpu.java:422)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:518)
	at legend.core.opengl.Window.run(Window.java:258)
	at legend.core.gpu.Gpu.run(Gpu.java:459)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by LordMonoxide** [comment] 2023-02-26 21:11
Closing as I can't reproduce, may have already been fixed

**Closed by LordMonoxide** 2023-02-26 21:11 UTC
Labels: bug
