### ISSUE TITLE
[OpenGL] On close/medium zoom levels, place text not showing on world map when holding Start button.

### ISSUE THREAD

**Issue by DrewUniverse** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#803] opened 2023-11-05 03:53 UTC
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/70291675/d84db8b9-0808-49cb-b813-d611c8a2b702)

**Comment by theflyingzamboni** [comment] 2023-12-15 20:40
This was a duplicate of #768

**Closed by theflyingzamboni** 2023-12-15 20:40 UTC
