### ISSUE TITLE
Meru doesn't perform victory dance.

### ISSUE THREAD

**Issue by Kona-lod** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#165] opened 2022-10-31 14:09 UTC
Meru just stands in her battle stance. I feel empty without her adorable tumble.
[Bug.zip](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/files/9901794/Bug.zip)
er adorable tumble.

Recreatable in attached save state by using Satchet on the Blue Bird. Will continue battle testing to see if it's common.

**Comment by Kona-lod** [comment] 2022-10-31 14:20
I'm bad at seeing stuff. Rose doesn't do victory dance and it appears Dart is the only one who does? lol

**Comment by DrewUniverse** [comment] 2022-12-16 02:51
To clarify on this, it's more that the character in slot one is the only one who will do a victory pose.

**Comment by LordMonoxide** [comment] 2023-01-03 02:14
Duplicate of #73

**Closed by LordMonoxide** 2023-01-03 02:14 UTC
Labels: bug, duplicate
